import 'dotenv/config';
import WebSocket from 'ws';
import { isStaffInteraction } from './src/permissions.js';
import { BRAND } from './src/branding.js';
import {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle} from 'discord.js';
for (const k of ['DISCORD_TOKEN','CLIENT_ID']) if (!process.env[k]?.trim()) throw new Error('Missing '+k);
if (!/^\d+$/.test(process.env.CLIENT_ID.trim())) throw new Error('CLIENT_ID must be numeric');
const PURPLE=BRAND.purple, RED=BRAND.red, refreshMs=Math.max(30,Number(process.env.RUST_REFRESH_SECONDS||60))*1000;
const config=new Map(), cache={data:null,at:0,error:null};
const rconCache=new Map();
const serverProfiles=new Map();
const searchPanels=new Map();
const command=new SlashCommandBuilder().setName('pop').setDescription('RustPulse live population dashboard').addSubcommand(s=>s.setName('view').setDescription('Show live population, server details, and players')).addSubcommand(s=>s.setName('players').setDescription('Show the connected player roster')).addSubcommand(s=>s.setName('status').setDescription('Show live server status and connection health')).addSubcommand(s=>s.setName('info').setDescription('Show public Rust server information returned by RCON')).addSubcommand(s=>s.setName('refresh').setDescription('Force a fresh server read; staff only')).addSubcommand(s=>s.setName('test').setDescription('Test RCON and player-list access; staff only')).addSubcommand(s=>s.setName('setup').setDescription('Configure automatic updates; staff only'));
const searchCommand=new SlashCommandBuilder().setName('searchplayer').setDescription('Find a connected RustPulse player').addStringOption(o=>o.setName('username').setDescription('Gamertag or player name').setRequired(true).setMaxLength(64));
const termsCommand=new SlashCommandBuilder().setName('terms').setDescription('View or post the RustPulse Pop terms').addChannelOption(o=>o.setName('target_channel').setDescription('Owner-only: post the terms in this channel').setRequired(false));
const rulesCommand=new SlashCommandBuilder().setName('rules').setDescription('View or post the RustPulse Pop rules').addChannelOption(o=>o.setName('target_channel').setDescription('Owner-only: post the rules in this channel').setRequired(false));
const helpCommand=new SlashCommandBuilder().setName('help').setDescription('Open the RustPulse Pop command guide');
const aboutCommand=new SlashCommandBuilder().setName('about').setDescription('Show RustPulse Pop capabilities and privacy boundary');
const pingCommand=new SlashCommandBuilder().setName('ping').setDescription('Check Discord latency and bot uptime');
const privacyCommand=new SlashCommandBuilder().setName('privacy').setDescription('Explain RustPulse Pop privacy and read-only boundaries');
const versionCommand=new SlashCommandBuilder().setName('version').setDescription('Show RustPulse Pop version and runtime details');
const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);
const register=async()=>{const guildRoute=process.env.GUILD_ID?Routes.applicationGuildCommands(process.env.CLIENT_ID,process.env.GUILD_ID):null;try{if(guildRoute){await rest.put(guildRoute,{body:[command.toJSON(),searchCommand.toJSON(),termsCommand.toJSON(),rulesCommand.toJSON(),helpCommand.toJSON(),aboutCommand.toJSON(),pingCommand.toJSON(),privacyCommand.toJSON(),versionCommand.toJSON()]});console.log('Registered commands for GUILD_ID '+process.env.GUILD_ID);}else{await rest.put(Routes.applicationCommands(process.env.CLIENT_ID),{body:[command.toJSON(),searchCommand.toJSON(),termsCommand.toJSON(),rulesCommand.toJSON(),helpCommand.toJSON(),aboutCommand.toJSON(),pingCommand.toJSON(),privacyCommand.toJSON(),versionCommand.toJSON()]));console.log('Registered global commands.');}}catch(error){if(error?.code===50001&&guildRoute){console.error('Discord denied access to GUILD_ID '+process.env.GUILD_ID+'. Check that this exact application is installed in that server and that GUILD_ID is correct. Falling back to global registration.');await rest.put(Routes.applicationCommands(process.env.CLIENT_ID),{body:[command.toJSON()]});console.log('Registered global commands; Discord propagation can take up to an hour.');}else throw error;}};
await register();
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const val=(x,f='Unavailable')=>x===undefined||x===null||x===''?f:String(x);
const isStaff=(i)=>isStaffInteraction(i);
const staffOnly=(i)=>{if(isStaff(i))return true;if(!i.replied&&!i.deferred)i.reply({content:'🔒 This command is limited to the server owner and staff with Administrator, Manage Server, or Manage Messages.',ephemeral:true});return false;};
function normalize(raw){const rows=Array.isArray(raw.players)?raw.players.map((p,i)=>typeof p==='string'?{name:p}:({name:p.name||p.username||'Unnamed survivor',platform:p.platform||p.device||'Platform unavailable',playing:p.playing||p.activity||'RustPulse'})):[];const n=raw.currentPlayers??raw.playersOnline??raw.online??raw.population??(Array.isArray(raw.players)?raw.players.length:null);return {serverName:raw.serverName||raw.name||process.env.RUST_SERVER_NAME||'RustPulse Server',current:Number.isFinite(Number(n))?Number(n):null,max:raw.maxPlayers??raw.capacity??null,rows};}
function parseEndpoint(p){const raw=(p.ip||p.host||'').trim();const m=raw.match(/^([^:]+)(?::(\\d+))?$/);if(!m)throw Error('Server host/IP must look like 203.0.113.10:28016');const host=p.host?.trim()||m[1];const port=Number(m[2]||p.rconPort||28016);if(!p.rconPassword)throw Error('RCON password is not configured');return {host,port};}
function parsePlayers(message){let text=typeof message==='string'?message:JSON.stringify(message);let parsed;try{parsed=JSON.parse(text);}catch{}const list=Array.isArray(parsed)?parsed:(parsed?.players||parsed?.Players||parsed?.data?.players);if(Array.isArray(list))return list.map((p,i)=>typeof p==='string'?{name:p,platform:'Console'}:{name:p.displayName||p.username||p.name||'Unnamed survivor',platform:p.platform||p.device||'Console',playing:p.playing||'RustPulse'});return text.split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean).filter(x=>!/^players?\\s*$/i.test(x)).map((x,i)=>({name:x.replace(/^[-*]\\s*/, '').slice(0,80),platform:'Console',playing:'RustPulse'}));}
function rconRequest(profile,command='global.playerlist'){const {host,port}=parseEndpoint(profile);const scheme=String(process.env.RCON_TLS||'').toLowerCase()==='true'?'wss':'ws';const url=scheme+'://'+host+':'+port+'/'+encodeURIComponent(profile.rconPassword);return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);try{ws.close()}catch{};fn(v);};const timer=setTimeout(()=>finish(reject,Error('RCON timed out after 10 seconds')),10000);ws.on('open',()=>ws.send(JSON.stringify({Identifier:1,Message:command,Name:'WebRcon',Type:'Generic'})));ws.on('message',raw=>{try{const packet=JSON.parse(raw.toString());if(packet.Identifier===1||packet.Message!==undefined)finish(resolve,packet.Message??packet);}catch{finish(reject,Error('RCON returned invalid JSON'));}});ws.on('error',err=>finish(reject,Error('RCON connection failed: '+err.message)));ws.on('close',()=>{if(!done)finish(reject,Error('RCON closed before replying'));});});}
function parseJsonOrText(message){if(typeof message!=='string')return message;try{return JSON.parse(message);}catch{return {text:message};}}
async function fetchRconSnapshot(guildId){const p=serverProfiles.get(guildId);if(!p)throw Error('Run /pop setup and configure the Rust server first');if(!p.rconPassword)throw Error('RCON password is missing. Open /pop setup and click Add RCON password.');const optional=async(command)=>{try{return {ok:true,data:await rconRequest(p,command)};}catch(error){return {ok:false,error:error.message};}};const [infoResult,playersResult,statusResult,usersResult]=await Promise.all([optional('server.info'),optional('playerlist'),optional('status'),optional('users')]);if(!playersResult.ok)throw Error('playerlist failed: '+playersResult.error);const info=parseJsonOrText(infoResult.ok?infoResult.data:{});const players=parseJsonOrText(playersResult.data);const rows=parsePlayers(players?.players??players?.Players??players?.data?.players??playersResult.data);const current=Number(info?.players??info?.currentPlayers??info?.online??info?.playerCount??rows.length);const d={serverName:p.name,current:Number.isFinite(current)?current:rows.length,max:info?.maxPlayers??info?.maxplayers??info?.capacity??null,rows,info,status:statusResult.ok?statusResult.data:null,users:usersResult.ok?usersResult.data:null,queue:info?.queue??info?.joining??null,map:info?.map??info?.level??null,checks:{serverInfo:infoResult.ok,playerlist:playersResult.ok,status:statusResult.ok,users:usersResult.ok}};rconCache.set(guildId,{data:d,at:Date.now(),error:null});return d;}
async function fetchRcon(guildId){return (await fetchRconSnapshot(guildId));}
async function getPop(guildId){const hit=rconCache.get(guildId);if(hit&&Date.now()-hit.at<refreshMs)return hit.data;try{return await fetchRcon(guildId)}catch(e){if(hit){hit.error=e.message;return hit.data}throw e;}}
async function testRcon(guildId){return await fetchRconSnapshot(guildId);}
function normalizeSearchPlayer(raw){return {name:String(raw?.DisplayName??raw?.displayName??raw?.Username??raw?.username??raw?.name??'Unknown survivor'),platform:String(raw?.OsBrand??raw?.platform??raw?.Platform??raw?.device??'Console'),id:raw?.UserId??raw?.userId??raw?.Id??raw?.id??null,ping:Number.isFinite(Number(raw?.Ping??raw?.ping))?Number(raw.Ping??raw.ping):null,seconds:Number.isFinite(Number(raw?.ConnectedSeconds??raw?.connectedSeconds))?Number(raw.ConnectedSeconds??raw.connectedSeconds):null};}
async function searchPlayer(guildId,query){const p=serverProfiles.get(guildId);if(!p?.rconPassword)throw Error('RCON password is missing');const raw=await rconRequest(p,'playerlist');let parsed;try{parsed=typeof raw==='string'?JSON.parse(raw):raw;}catch{throw Error('RCON returned an unreadable player list');}const list=Array.isArray(parsed)?parsed:(parsed?.players||parsed?.Players||parsed?.data?.players);if(!Array.isArray(list))throw Error('RCON returned no readable players');const q=query.toLowerCase();return list.map(normalizeSearchPlayer).find(x=>x.name.toLowerCase().includes(q))||null;}
function searchCard(p,q){const platform=String(p.platform||'Console');const badge=platform.toLowerCase().includes('xbox')?'🟢 Xbox':platform.toLowerCase().includes('playstation')||platform.toLowerCase().includes('psn')?'🔵 PlayStation':'🎮 '+platform;const ping=p.ping===null?'⚪ Not returned':p.ping<80?'🟢 '+p.ping+' ms • Stable':p.ping<160?'🟡 '+p.ping+' ms • Fair':'🔴 '+p.ping+' ms • High';const session=p.seconds===null?'Not returned':p.seconds<3600?Math.max(1,Math.floor(p.seconds/60))+' min':Math.floor(p.seconds/3600)+'h '+Math.floor((p.seconds%3600)/60)+'m';return brand('🔎 PLAYER SIGNAL // PRIVATE').setColor(PURPLE).setDescription('**RUST CONSOLE NETWORK SEARCH**\n\n╭─ ACTIVE SURVIVOR LOCATED ─╮\n　Read-only live lookup from RCON.').addFields({name:'🎯 QUERY',value:q.slice(0,80),inline:true},{name:'🟢 PRESENCE',value:'Online & active',inline:true},{name:'🎮 GAMERTAG',value:p.name.slice(0,100),inline:true},{name:'🌐 CONSOLE NETWORK',value:badge,inline:true},{name:'📡 NETWORK LATENCY',value:ping,inline:true},{name:'⏳ ACTIVE SESSION',value:session,inline:true},{name:'🛡️ PLATFORM ID',value:p.id?'Available • hidden':'Not returned',inline:true},{name:'🔒 PRIVACY BOUNDARY',value:'No server address, port, region, credentials, profile links, or moderation actions are exposed.'}).setFooter({text:'RustPulse Pop • Free • read-only'});}
const searchControls=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('search_refresh').setLabel('Refresh signal').setEmoji('🔄').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('search_dismiss').setLabel('Close panel').setEmoji('✖️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('search_privacy').setLabel('Privacy').setEmoji('🛡️').setStyle(ButtonStyle.Secondary));
const infoControls=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('info_terms').setLabel('Terms of use').setEmoji('📜').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('info_rules').setLabel('Community rules').setEmoji('🛡️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('info_privacy').setLabel('Privacy & safety').setEmoji('🔒').setStyle(ButtonStyle.Secondary));
const infoSections=()=>new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('info_section').setPlaceholder('Open the guide').addOptions({label:'Start here',value:'start',emoji:'🧭'},{label:'Discord conduct',value:'discord',emoji:'💬'},{label:'In-game conduct',value:'game',emoji:'🎮'},{label:'Setup guide',value:'setup',emoji:'🛠️'},{label:'Commands',value:'commands',emoji:'⚡'},{label:'RCON and privacy',value:'rcon',emoji:'🔐'},));
const infoFooter='RUSTPULSE POP • Free community tool • Keep the coast clean';
function rulesHub(){return brand('🛡️ OFFICIAL RULES & GUIDELINES').setDescription('**Welcome to the RustPulse Pop guide.**\n\nEverything you need is behind the buttons below: how to behave, how to connect a server, what each command does, and what information must stay private.\n\n**🟠 General information**\nThis bot is free and read-only. It shows live fields returned by an authorised RCON connection; it does not invent missing data.\n\n**📚 Use the guide**\nChoose a section from the menu, or use the buttons to switch between the full terms, rules, and privacy pages.').addFields({name:'🚀 Quick start',value:'1. The server owner runs /pop setup.\n2. Choose Setup server and enter the server details.\n3. Add the RCON password through the private modal.\n4. Run /pop test.\n5. Use /pop view to open the live dashboard.'},{name:'📌 Important',value:'Never post passwords, tokens, webhook URLs, IP addresses, or private screenshots. If one is exposed, rotate it immediately.'}).setFooter({text:infoFooter});}
function sectionEmbed(value){const sections={start:['🧭 START HERE','RustPulse Pop is a free, read-only Discord tool. The server owner controls setup. Start with /pop setup, finish the private RCON prompt, run /pop test, then use /pop view.'],discord:['💬 DISCORD CONDUCT','Be respectful. No harassment, threats, hate speech, targeted humiliation, spam, or attempts to expose private information. Follow Discord Terms and local staff instructions.'],game:['🎮 IN-GAME CONDUCT','Play fairly and follow the Rust server rules. Do not use player tracking to target, intimidate, stalk, or publish information about another player.'],setup:['🛠️ SETUP GUIDE','Only the Discord server owner can configure the bot. Run /pop setup, choose Setup server, enter the server name, IPv4 address, RCON port, region, and optional description, then submit. Click Add RCON password and enter it in the private modal. Run /pop test; a successful test confirms the bot can read the player list. Choose automatic updates last.'],commands:['⚡ COMMAND GUIDE','/pop view opens the live population and roster.\n/pop status shows connection health and the last successful check.\n/pop test checks RCON and the player list; it is owner-only.\n/pop setup opens the owner control panel.\n/searchplayer username privately looks up a connected player for an authorised manager or owner.\n/terms and /rules open this guide; the owner can add target_channel to post a panel publicly.'],rcon:['🔐 RCON, DATA & PRIVACY','Use only a server you are authorised to monitor. Keep the RCON password, Discord token, webhook URL, IP address, and private screenshots out of chat and GitHub. Public population panels hide connection details. Player fields are limited to what RCON returns. Do not scrape, resell, redistribute, stalk, or profile players.']};const [title,text]=sections[value]||sections.start;return brand(title).setDescription(text+'\n\nUse the buttons above to switch pages or open another guide section.').setFooter({text:infoFooter});}
function termsEmbed(){return brand('📜 OFFICIAL TERMS OF USE').setDescription('**Please read before using RustPulse Pop.**\n\nThis is a free tool that presents live information returned by an authorised RustPulse RCON connection.').addFields({name:'🆓 Free community service',value:'The bot is free to use. Features, hosting, limits, and availability may change.'},{name:'📡 Source-dependent data',value:'Counts, player fields, ping, map, queue, and status appear only when the server returns them.'},{name:'👑 Authorised access',value:'Only connect a server you own or have clear permission to monitor.'},{name:'🔐 Secrets',value:'Never share RCON passwords, Discord tokens, webhook URLs, API keys, IP addresses, or private screenshots.'},{name:'🧑‍🚀 Player information',value:'Use player details for ordinary community visibility only. Do not harass, dox, threaten, or redistribute them.'},{name:'🛡️ Read-only boundary',value:'The bot does not provide kick, ban, warning, or other destructive server actions.'},{name:'✅ Agreement',value:'Use of the bot means you agree to these boundaries, Discord Terms, and the Rust server local rules.'}).setFooter({text:infoFooter});}
function rulesEmbed(){return rulesHub();}
const brand=t=>new EmbedBuilder().setColor(PURPLE).setTitle('⚡ '+t).setAuthor({name:'RUSTPULSE POP // LIVE INTELLIGENCE'}).setFooter({text:'RustPulse Pop • read-only • source-dependent'}).setTimestamp();
function dashboard(d, meta = {}) {
  const updated = meta.at || Date.now();
  const stale = Boolean(meta.error);
  const count = Number.isFinite(Number(d.current)) ? Number(d.current) : d.rows.length;
  const capacity = d.max !== null && d.max !== undefined ? String(d.max) : '—';
  const occupancy = d.max ? Math.min(100, Math.round((count / Number(d.max)) * 100)) : null;
  const bar = occupancy === null ? '░░░░░░░░░░' : '█'.repeat(Math.round(occupancy / 10)) + '░'.repeat(10 - Math.round(occupancy / 10));
  const state = stale ? '🟠 DELAYED' : '🟢 LIVE';
  const headline = count === 0 ? 'The coast is quiet.' : count === 1 ? 'One survivor is online.' : count + ' survivors are online.';
  const e = brand('LIVE SERVER PULSE').setDescription('**' + String(d.serverName || 'Rust server').slice(0, 100) + '**\n' + headline + '\n\n' + bar + (occupancy === null ? '' : '  **' + occupancy + '%** capacity') + (stale ? '\n\n⚠️ This is the last successful snapshot.' : '')).addFields({name:'📡 SIGNAL',value:state,inline:true},{name:'👥 ONLINE',value:'**' + count + '** / ' + capacity,inline:true},{name:'🕒 FRESHNESS',value:'<t:' + Math.floor(updated / 1000) + ':R>',inline:true});
  const pulse=[]; if(d.map) pulse.push('🗺️ **Map**\n' + String(d.map).slice(0, 80)); if(d.queue !== null && d.queue !== undefined) pulse.push('⏳ **Queue**\n' + String(d.queue)); if(d.region) pulse.push('📍 **Region**\n' + String(d.region).slice(0, 60)); if(pulse.length) e.addFields({name:'SERVER TELEMETRY',value:pulse.join('     ')});
  if(d.rows.length) e.addFields({name:'🧑‍🚀 ACTIVE ROSTER  •  ' + d.rows.length + ' listed',value:d.rows.slice(0, 20).map((p,i)=>'**' + String(i+1).padStart(2,'0') + '  ' + val(p.name,'Unknown survivor') + '**  ·  ' + val(p.platform,'Console') + (p.ping ? '  ·  ' + p.ping + 'ms' : '')).join('\n').slice(0, 3900)});
  else e.addFields({name:'🧑‍🚀 ACTIVE ROSTER',value:count === 0 ? 'No connected players were returned.' : 'The server returned population but no individual roster.'});
  e.addFields({name:'🛡️ PRIVACY BY DESIGN',value:'Public view hides IP, RCON port, region, credentials, and private configuration. Missing fields remain unavailable.'});
  return e;
}

const controls=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('refresh').setLabel('Refresh signal').setEmoji('🔄').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('status').setLabel('Connection').setEmoji('📡').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('copyless').setLabel('Privacy').setEmoji('🛡️').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('view_mode').setPlaceholder('Choose a dashboard view').addOptions({label:'Live roster',value:'roster',emoji:'🧑‍🚀'},{label:'Server pulse',value:'pulse',emoji:'📊'},{label:'How it works',value:'help',emoji:'❔'}))];
const setupButtons=(guildId)=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('server_add').setLabel(serverProfiles.has(guildId)?'Edit server':'Setup server').setEmoji(serverProfiles.has(guildId)?'🛠️':'🚀').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('server_view').setLabel('Review setup').setEmoji('📋').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('server_clear').setLabel('Disconnect').setEmoji('⛔').setStyle(ButtonStyle.Danger));
const rconSetupButton=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('rco_add').setLabel('Add RCON password').setEmoji('🔐').setStyle(ButtonStyle.Primary));
const updateSetup=()=>new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('setup').setPlaceholder('Choose how the live count should appear').addOptions({label:'Off',value:'off',emoji:'⏸️'},{label:'Bot status',value:'bio',emoji:'🟣'},{label:'Channel embed',value:'channel',emoji:'📣'},{label:'Both',value:'both',emoji:'⚡'}));
const serverModal=()=>new ModalBuilder().setCustomId('server_modal').setTitle('🛠️ Rust server details').addComponents(
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('server_name').setLabel('Server name').setPlaceholder('The name your players recognise').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('ip').setLabel('Server IP address').setPlaceholder('IPv4 address from your server host').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(80)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('rcon_port').setLabel('RCON port').setPlaceholder('RCON port from your host').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(10)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('region').setLabel('Region').setPlaceholder('Where this server is hosted').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(40)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Description (optional)').setPlaceholder('A short description for this server').setStyle(TextInputStyle.Paragraph).setRequired(false).setMaxLength(500))
);
const credentialModal=()=>new ModalBuilder().setCustomId('credential_modal').setTitle('🔐 RCON credentials').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('rco_password').setLabel('RCON password').setPlaceholder('Entered privately — never posted').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(200)));
const profileCard=(p)=>brand('SERVER PROFILE // PRIVATE').setDescription('Configuration is restricted to the server owner. Sensitive connection details are redacted from this view.').addFields({name:'🧱 Server',value:p.name,inline:true},{name:'🔐 RCON',value:p.rconPassword?'Configured • hidden':'Not configured',inline:true},{name:'🛡️ Visibility',value:'Owner-only',inline:true},{name:'📝 Description',value:p.description||'No description'});
async function status(){const e=brand('POP STATUS').addFields({name:'Source configured',value:process.env.RUST_STATUS_URL?'✅ Yes':'❌ No',inline:true},{name:'Connection',value:cache.error?'🔴 Error':cache.data?'🟢 Healthy':'⚪ Not checked',inline:true},{name:'Last update',value:cache.at?'<t:'+Math.floor(cache.at/1000)+':R>':'Never',inline:true});if(cache.error)e.addFields({name:'Safe error',value:cache.error.slice(0,900)});return e;}
client.on('interactionCreate', async (i) => {
  try {
    if (i.isChatInputCommand()) {
      const sub = i.commandName === 'pop' ? i.options.getSubcommand() : null;
      if (i.commandName === 'privacy') return i.reply({embeds:[brand('🛡️ PRIVACY // READ-ONLY PROMISE').setDescription('RustPulse Pop is designed to show server information without exposing private infrastructure.').addFields({name:'Public panels hide',value:'Server IP, RCON port, passwords, Discord tokens, webhook URLs, and private setup.'},{name:'Data source',value:'Only fields returned by an authorised Rust Console RCON connection are displayed. Missing fields remain unavailable.'},{name:'Player safety',value:'Player details are for ordinary community visibility only. Do not harass, stalk, dox, scrape, or redistribute them.'},{name:'Action boundary',value:'RustPulse Pop does not kick, ban, warn, modify, or perform destructive server actions.'})],ephemeral:true});
      if (i.commandName === 'version') return i.reply({embeds:[brand('⚡ RUSTPULSE POP // BUILD INFO').setDescription('Rust Console population intelligence for Discord.').addFields({name:'Version',value:'1.0.0',inline:true},{name:'Runtime',value:'Node.js + discord.js v14',inline:true},{name:'Transport',value:'Facepunch WebRCON over WebSocket',inline:true},{name:'Mode',value:'Read-only',inline:true},{name:'Commands',value:'Public dashboards, staff setup, RCON checks, and private lookup',inline:false})]});
      if (i.commandName === 'ping') return i.reply({embeds:[brand('🏓 PONG // SYSTEM SIGNAL').setDescription('RustPulse Pop is awake and listening.').addFields({name:'Discord round trip',value:(Date.now()-i.createdTimestamp)+' ms',inline:true},{name:'WebSocket',value:client.ws.ping+' ms',inline:true},{name:'Uptime',value:Math.floor(process.uptime()/60)+' minutes',inline:true})]});
      if (i.commandName === 'about') return i.reply({embeds:[brand('⚡ ABOUT RUSTPULSE POP').setDescription('A polished, read-only Rust Console population bot for Discord.').addFields({name:'What it does',value:'Live population, server info, roster views, RCON checks, staff lookup, setup, rules, and terms.'},{name:'What it never does',value:'No kick, ban, warning, credential forwarding, webhook relay, public tunnel, or destructive action.'},{name:'Data boundary',value:'Only authorised RCON fields are displayed; missing data stays unavailable.'})]});
      if (i.commandName === 'help') return i.reply({embeds:[brand('📚 RUSTPULSE POP // COMMAND GUIDE').setDescription('Safe read-only tools for your Rust Console server.').addFields({name:'Public',value:'/pop view — live dashboard\n/pop players — connected roster\n/pop info — server metadata\n/pop status — connection health\n/ping — latency\n/about — capabilities'},{name:'Staff',value:'/pop refresh — fresh RCON read\n/pop test — verify RCON\n/pop setup — configure server\n/searchplayer — private lookup\n/rules and /terms — community panels'},{name:'Privacy',value:'IP, port, credentials, tokens, and private configuration stay hidden.'})],ephemeral:true});
      if (i.commandName === 'terms') { const target=i.options.getChannel('target_channel'); if(target){if(!staffOnly(i))return;if(!target.isTextBased())return i.reply({content:'⚠️ Choose a text-based channel.',ephemeral:true});await target.send({embeds:[termsEmbed()],components:[infoControls(),infoSections()]});return i.reply({content:'✅ Terms posted in '+target+'.',ephemeral:true});}return i.reply({embeds:[termsEmbed()],components:[infoControls(),infoSections()],ephemeral:true});}
      if (i.commandName === 'rules') { const target=i.options.getChannel('target_channel'); if(target){if(!staffOnly(i))return;if(!target.isTextBased())return i.reply({content:'⚠️ Choose a text-based channel.',ephemeral:true});await target.send({embeds:[rulesHub()],components:[infoControls(),infoSections()]});return i.reply({content:'✅ Rules posted in '+target+'.',ephemeral:true});}return i.reply({embeds:[rulesHub()],components:[infoControls(),infoSections()],ephemeral:true});}
      if (i.commandName === 'searchplayer') { if (!i.guild) return i.reply({content:'This command can only be used in a server.',ephemeral:true}); if (!staffOnly(i)) return; const q=i.options.getString('username',true).trim(); if(!serverProfiles.get(i.guild.id)) return i.reply({content:'⚙️ Run /pop setup first.',ephemeral:true}); if(!serverProfiles.get(i.guild.id).rconPassword) return i.showModal(credentialModal()); await i.deferReply({ephemeral:true}); try {const p=await searchPlayer(i.guild.id,q); if(!p)return i.editReply({embeds:[brand('🔎 NO ACTIVE MATCH').setDescription('No connected player matched '+q+'.') ]}); const msg=await i.editReply({embeds:[searchCard(p,q)],components:[searchControls()]}); searchPanels.set(msg.id,{guildId:i.guild.id,query:q,ownerId:i.user.id});} catch(error){return i.editReply({embeds:[brand('🔎 SEARCH UNAVAILABLE').setColor(RED).setDescription('The live player list could not be read.').addFields({name:'Reason',value:String(error.message).slice(0,900)})]});} return; }
      if (sub === 'players') { if (!i.guild) return i.reply({content:'This command can only be used in a server.',ephemeral:true}); await i.deferReply(); try { const d=await getPop(i.guild.id); const roster=d.rows.length?d.rows.slice(0,40).map((p,n)=>'**'+String(n+1).padStart(2,'0')+'**  '+val(p.name,'Unknown survivor')+'  ·  '+val(p.platform,'Console')).join('\n'):'No connected players were returned.'; return i.editReply({embeds:[brand('🧑‍🚀 LIVE ROSTER').setDescription('Connected players returned by authorised RCON.').addFields({name:'Online',value:String(d.current),inline:true},{name:'Listed',value:String(d.rows.length),inline:true},{name:'Players',value:roster.slice(0,3900)})]}); } catch(error) { return i.editReply({embeds:[brand('🧑‍🚀 ROSTER UNAVAILABLE').setColor(RED).setDescription('The live roster could not be read.').addFields({name:'Safe error',value:String(error.message).slice(0,900)})]}); } }
      if (sub === 'refresh') { if (!staffOnly(i)) return; if (!i.guild) return i.reply({content:'This command can only be used in a server.',ephemeral:true}); await i.deferReply({ephemeral:true}); try { const d=await fetchRcon(i.guild.id); return i.editReply({embeds:[brand('🔄 FRESH SIGNAL RECEIVED').setDescription('The server was queried now and the cache refreshed.').addFields({name:'Server',value:String(d.serverName).slice(0,100),inline:true},{name:'Online',value:String(d.current),inline:true},{name:'Checked',value:'<t:'+Math.floor(Date.now()/1000)+':R>',inline:true})]}); } catch(error) { return i.editReply({embeds:[brand('🔄 REFRESH FAILED').setColor(RED).setDescription('The server could not be refreshed.').addFields({name:'Safe error',value:String(error.message).slice(0,900)})]}); } }
      if (sub === 'info') { if (!i.guild) return i.reply({content:'This command can only be used in a server.',ephemeral:true}); await i.deferReply(); try { const d=await getPop(i.guild.id); const info=d.info&&typeof d.info==='object'?d.info:{}; const value=(...keys)=>{for(const k of keys){if(info[k]!==undefined&&info[k]!==null&&String(info[k]).trim())return String(info[k]).slice(0,100);}return 'Not returned';}; const players=d.current===null?'Not returned':String(d.current)+(d.max!==null?' / '+d.max:''); const embed=brand('📡 SERVER INFO // PUBLIC').setDescription('Read-only information returned by the authorised Rust RCON server. Private connection details and credentials are never shown.').addFields({name:'🏷️ Server',value:String(d.serverName||'Rust server').slice(0,100),inline:true},{name:'👥 Population',value:players,inline:true},{name:'🗺️ Map / Level',value:String(d.map||value('map','level','Level','Map')),inline:true},{name:'🌐 Address',value:'Hidden for privacy',inline:true},{name:'🎮 Queue',value:d.queue===null?'Not returned':String(d.queue).slice(0,100),inline:true},{name:'⚡ FPS',value:value('fps','FPS','frameRate'),inline:true},{name:'📍 Region',value:String(serverProfiles.get(i.guild.id)?.region||'Not configured').slice(0,100),inline:true},{name:'🔄 Last checked',value:'<t:'+Math.floor(Date.now()/1000)+':R>',inline:true},{name:'🛡️ Data boundary',value:'Only fields returned by RCON are displayed. Missing values remain unavailable.'}).setFooter({text:'RustPulse Pop • Free • read-only'}); return i.editReply({embeds:[embed]}); } catch(error) { return i.editReply({embeds:[brand('📡 SERVER INFO UNAVAILABLE').setColor(RED).setDescription('The server information could not be read.').addFields({name:'Safe error',value:String(error.message).slice(0,900)})]}); } }
      if (sub === 'setup') {
        if (!staffOnly(i)) return;
        return i.reply({ embeds: [brand('SERVER CONTROL // OWNER PANEL').setDescription('One place to manage the Rust server behind this bot. Set the connection once, test it, then choose where the live population should appear.').addFields({ name: 'Connection', value: serverProfiles.has(i.guild.id) ? '🟢 Ready to test' : '⚪ Setup required', inline: true }, { name: 'Live count', value: config.get(i.guild.id) === 'off' || !config.get(i.guild.id) ? '⏸️ Disabled' : '🟢 ' + config.get(i.guild.id), inline: true }, { name: 'Recommended flow', value: serverProfiles.has(i.guild.id) ? 'Run /pop test, then choose an automatic update mode.' : 'Start with Edit server and enter the RCON details.' })], components: serverProfiles.get(i.guild.id)?.rconPassword ? [setupButtons(i.guild.id), updateSetup()] : [setupButtons(i.guild.id), rconSetupButton(), updateSetup()], ephemeral: true });
      }
      if (sub === 'test') {
        if (!staffOnly(i)) return;
        const profile = serverProfiles.get(i.guild.id);
        if (!profile) return i.reply({ content: '⚙️ Run /pop setup first and configure the Rust server.', ephemeral: true });
        if (!profile.rconPassword) return i.showModal(credentialModal());
        await i.deferReply({ ephemeral: true });
        try { const d = await testRcon(i.guild.id); return i.editReply({ embeds: [brand('RCON TEST PASSED').setDescription('✅ RCON connected and returned a player list.').addFields({ name: 'Server', value: d.serverName, inline: true }, { name: 'Players returned', value: String(d.current), inline: true }, { name: 'Next', value: 'Run /pop view.' })] }); }
        catch (error) { return i.editReply({ embeds: [brand('RCON TEST FAILED').setColor(RED).setDescription('❌ The bot could not connect or read the player list.').addFields({ name: 'Reason', value: String(error.message).slice(0, 900) }, { name: 'Check', value: 'Verify host/IP, RCON port, password, and provider settings.' })] }); }
      }
      if (sub === 'status') return i.reply({ embeds: [await status()], ephemeral: true });
      if (!i.guild) return i.reply({ content: 'This command can only be used in a Discord server.', ephemeral: true });
      const profile = serverProfiles.get(i.guild.id);
      if (!profile) return i.reply({ content: '⚙️ Run /pop setup first and configure the Rust server.', ephemeral: true });
      if (!profile.rconPassword) return i.showModal(credentialModal());
      await i.deferReply();
      try { const d = await getPop(i.guild.id); return i.editReply({ embeds: [dashboard(d, rconCache.get(i.guild.id) || {})], components: controls() }); }
      catch (error) { return i.editReply({ embeds: [brand('POP FEED OFFLINE').setColor(RED).setDescription('No live population was displayed.').addFields({ name: 'Reason', value: String(error.message).slice(0, 900) })] }); }
    }
    if (i.isButton() && ['info_terms','info_rules','info_privacy'].includes(i.customId)) { if(i.customId==='info_terms')return i.update({embeds:[termsEmbed()],components:[infoControls(),infoSections()]}); if(i.customId==='info_rules')return i.update({embeds:[rulesHub()],components:[infoControls(),infoSections()]}); return i.reply({embeds:[sectionEmbed('privacy')],ephemeral:true}); }
    if (i.isButton() && (i.customId === 'search_refresh' || i.customId === 'search_dismiss')) { const panel=searchPanels.get(i.message.id); if(!panel||panel.ownerId!==i.user.id)return i.reply({content:'🔒 This private panel belongs to another operator.',ephemeral:true}); if(i.customId==='search_dismiss'){searchPanels.delete(i.message.id);return i.update({embeds:[brand('SEARCH CLOSED').setDescription('Private player panel closed.')],components:[]});} await i.deferUpdate(); try {const p=await searchPlayer(panel.guildId,panel.query); if(!p)return i.editReply({embeds:[brand('🔎 NO ACTIVE MATCH').setDescription('That player is no longer connected.')],components:[searchControls()]}); return i.editReply({embeds:[searchCard(p,panel.query)],components:[searchControls()]});} catch(error){return i.followUp({content:'⚠️ Refresh failed: '+String(error.message).slice(0,900),ephemeral:true});} }
    if (i.isButton()) {
      if (i.customId === 'server_add') { if (!staffOnly(i)) return; try { return await i.showModal(serverModal()); } catch (error) { if (error?.code === 10062) return; throw error; } }
      if (i.customId === 'rco_add') { if (!staffOnly(i)) return; try { return await i.showModal(credentialModal()); } catch (error) { if (error?.code === 10062) return; throw error; } }
      if (i.customId === 'server_view') { if (!staffOnly(i)) return; const p = serverProfiles.get(i.guild.id); return i.reply({ embeds: [p ? profileCard(p) : brand('NO SERVER PROFILE').setDescription('Configure a server first.')], ephemeral: true }); }
      if (i.customId === 'server_clear') { if (!staffOnly(i)) return; serverProfiles.delete(i.guild.id); return i.reply({ content: '🗑️ Rust server profile cleared from memory.', ephemeral: true }); }
      if (i.customId === 'status') return i.reply({ embeds: [await status()], ephemeral: true });
      if (i.customId === 'refresh') { await i.deferUpdate(); try { const d = await fetchRcon(i.guild.id); return i.editReply({ embeds: [dashboard(d, rconCache.get(i.guild.id) || {})], components: controls() }); } catch (error) { return i.followUp({ content: '⚠️ Live refresh failed: ' + String(error.message).slice(0, 900), ephemeral: true }); } }
    }
    if (i.isStringSelectMenu() && i.customId === 'view_mode') {
      const mode = i.values[0];
      if (mode === 'help') return i.reply({ embeds: [brand('POP // FIELD GUIDE').setDescription('🟣 **Live roster** shows player rows returned by RCON.\\n📊 **Server pulse** shows capacity, queue, and map when the server provides them.\\n🛡️ **Privacy mode** keeps connection details out of public embeds.')], ephemeral: true });
      const cached = rconCache.get(i.guild.id)?.data;
      if (!cached) return i.reply({ content: 'Run /pop view first to load the live signal.', ephemeral: true });
      if (mode === 'pulse') return i.update({ embeds: [brand('📊 SERVER PULSE').setDescription('**RustPulse operational snapshot**').addFields({ name: 'Online', value: String(cached.current), inline: true }, { name: 'Capacity', value: val(cached.max, 'Not returned'), inline: true }, { name: 'Queue', value: val(cached.queue, 'Not returned'), inline: true }, { name: 'Map', value: val(cached.map, 'Not returned') }, { name: 'Checks', value: 'server.info ' + (cached.checks?.serverInfo ? '✅' : '—') + '  playerlist ' + (cached.checks?.playerlist ? '✅' : '❌') + '  status ' + (cached.checks?.status ? '✅' : '—') + '  users ' + (cached.checks?.users ? '✅' : '—') })], components: controls() });
      return i.update({ embeds: [dashboard(cached, rconCache.get(i.guild.id) || {})], components: controls() });
    }
    if (i.isButton() && i.customId === 'copyless') return i.reply({ embeds: [brand('🛡️ PRIVACY MODE').setDescription('Public panels show population and returned player details only. IP, port, region, credentials, and private server configuration remain hidden.')], ephemeral: true });
    if (i.isStringSelectMenu() && i.customId === 'info_section') { return i.update({embeds:[sectionEmbed(i.values[0])],components:[infoControls(),infoSections()]}); }
    if (i.isModalSubmit()) {
      if (!staffOnly(i)) return;
      if (i.customId === 'server_modal') {
        const p = { name: i.fields.getTextInputValue('server_name').trim(), ip: i.fields.getTextInputValue('ip').trim(), rconPort: i.fields.getTextInputValue('rcon_port').trim(), region: i.fields.getTextInputValue('region').trim(), description: i.fields.getTextInputValue('description').trim() };
        if (!/^\d{1,3}(?:\.\d{1,3}){3}$/.test(p.ip)) return i.reply({ content: '⚠️ Enter the Rust server IPv4 address only, for example 203.0.113.10.', ephemeral: true }); if (!/^\d{1,5}$/.test(p.rconPort) || Number(p.rconPort) < 1 || Number(p.rconPort) > 65535) return i.reply({ content: '⚠️ Enter a valid RCON port.', ephemeral: true });
        serverProfiles.set(i.guild.id, p);
        return i.reply({ content: '✅ Server details saved. Use **Edit server** any time to change them. Add the RCON password to finish the connection.', components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('rco_add').setLabel('Add RCON password').setEmoji('🔐').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId('server_add').setLabel('Edit server').setEmoji('🛠️').setStyle(ButtonStyle.Secondary))], ephemeral: true });
      }
      if (i.customId === 'credential_modal') { const p = serverProfiles.get(i.guild.id); if (!p) return i.reply({ content: 'Configure server details first.', ephemeral: true }); const password = i.fields.getTextInputValue('rco_password').trim(); if (!password) return i.reply({ content: '⚠️ Enter the RCON password before submitting.', ephemeral: true }); p.rconPassword = password; serverProfiles.set(i.guild.id, p); await i.deferReply({ ephemeral: true }); try { const d = await testRcon(i.guild.id); return i.editReply({ embeds: [brand('RCON CONNECTED').setDescription('✅ Password accepted. RCON connected and the player list is available.').addFields({ name: 'Server', value: d.serverName, inline: true }, { name: 'Players online', value: String(d.current), inline: true }, { name: 'Next', value: 'Run /pop view to open the full player list.' })] }); } catch (error) { p.rconPassword = undefined; serverProfiles.set(i.guild.id, p); return i.editReply({ embeds: [brand('RCON PASSWORD NOT VERIFIED').setColor(RED).setDescription('The password was saved only for this test, but the server rejected the connection.').addFields({ name: 'Reason', value: String(error.message).slice(0, 900) }, { name: 'Check', value: 'Confirm the RCON password, server IP, RCON port, and that RCON is enabled.' })] }); } }
    }
    if (i.isStringSelectMenu() && i.customId === 'setup') { if (!staffOnly(i)) return; config.set(i.guild.id, i.values[0]); return i.update({ embeds: [brand('SETUP SAVED').setDescription('Automatic updates: **' + i.values[0] + '**')], components: [] }); }
  } catch (error) { console.error('[interaction]', error); if (!i.replied && !i.deferred) await i.reply({ content: '⚠️ Unexpected error. Check hosting logs.', ephemeral: true }); }
});
client.once('clientReady', () => {
  console.log('RustPulse Pop online as ' + client.user.tag);
  setInterval(async () => {
    for (const [guildId, mode] of config) {
      if (mode !== 'bio' && mode !== 'both') continue;
      try {
        const d = await getPop(guildId);
        client.user.setPresence({ activities: [{ name: (d.current ?? '—') + ' online • /pop' }], status: 'online' });
      } catch (error) {
        console.error('[bio]', error.message);
      }
    }
  }, refreshMs);
});
await client.login(process.env.DISCORD_TOKEN);
