import 'dotenv/config';
import WebSocket from 'ws';
import {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle} from 'discord.js';
for (const k of ['DISCORD_TOKEN','CLIENT_ID']) if (!process.env[k]?.trim()) throw new Error('Missing '+k);
if (!/^\d+$/.test(process.env.CLIENT_ID.trim())) throw new Error('CLIENT_ID must be numeric');
const PURPLE=0xb026ff, RED=0xed4245, refreshMs=Math.max(30,Number(process.env.RUST_REFRESH_SECONDS||60))*1000;
const config=new Map(), cache={data:null,at:0,error:null};
const rconCache=new Map();
const serverProfiles=new Map();
const searchPanels=new Map();
const command=new SlashCommandBuilder().setName('pop').setDescription('Rust Console live population dashboard').addSubcommand(s=>s.setName('view').setDescription('Show live population, server details, and players')).addSubcommand(s=>s.setName('status').setDescription('Show live server status and connection health')).addSubcommand(s=>s.setName('test').setDescription('Test RCON and player-list access; owner only')).addSubcommand(s=>s.setName('setup').setDescription('Configure automatic updates; server owner only'));
const searchCommand=new SlashCommandBuilder().setName('searchplayer').setDescription('Find a connected Rust Console player').addStringOption(o=>o.setName('username').setDescription('Gamertag or player name').setRequired(true).setMaxLength(64));
const termsCommand=new SlashCommandBuilder().setName('terms').setDescription('View Rust Console Pop terms, privacy, and usage boundaries');
const rulesCommand=new SlashCommandBuilder().setName('rules').setDescription('View the Rust Console Pop community rules');
const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);
const register=async()=>{const guildRoute=process.env.GUILD_ID?Routes.applicationGuildCommands(process.env.CLIENT_ID,process.env.GUILD_ID):null;try{if(guildRoute){await rest.put(guildRoute,{body:[command.toJSON(),searchCommand.toJSON(),termsCommand.toJSON(),rulesCommand.toJSON()]});console.log('Registered commands for GUILD_ID '+process.env.GUILD_ID);}else{await rest.put(Routes.applicationCommands(process.env.CLIENT_ID),{body:[command.toJSON()]});console.log('Registered global commands.');}}catch(error){if(error?.code===50001&&guildRoute){console.error('Discord denied access to GUILD_ID '+process.env.GUILD_ID+'. Check that this exact application is installed in that server and that GUILD_ID is correct. Falling back to global registration.');await rest.put(Routes.applicationCommands(process.env.CLIENT_ID),{body:[command.toJSON()]});console.log('Registered global commands; Discord propagation can take up to an hour.');}else throw error;}};
await register();
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const val=(x,f='Unavailable')=>x===undefined||x===null||x===''?f:String(x);
function normalize(raw){const rows=Array.isArray(raw.players)?raw.players.map((p,i)=>typeof p==='string'?{name:p}:({name:p.name||p.username||'Unnamed survivor',platform:p.platform||p.device||'Platform unavailable',playing:p.playing||p.activity||'Rust Console'})):[];const n=raw.currentPlayers??raw.playersOnline??raw.online??raw.population??(Array.isArray(raw.players)?raw.players.length:null);return {serverName:raw.serverName||raw.name||process.env.RUST_SERVER_NAME||'Rust Console Server',current:Number.isFinite(Number(n))?Number(n):null,max:raw.maxPlayers??raw.capacity??null,rows};}
function parseEndpoint(p){const raw=(p.ip||p.host||'').trim();const m=raw.match(/^([^:]+)(?::(\\d+))?$/);if(!m)throw Error('Server host/IP must look like 203.0.113.10:28016');const host=p.host?.trim()||m[1];const port=Number(m[2]||p.rconPort||28016);if(!p.rconPassword)throw Error('RCON password is not configured');return {host,port};}
function parsePlayers(message){let text=typeof message==='string'?message:JSON.stringify(message);let parsed;try{parsed=JSON.parse(text);}catch{}const list=Array.isArray(parsed)?parsed:(parsed?.players||parsed?.Players||parsed?.data?.players);if(Array.isArray(list))return list.map((p,i)=>typeof p==='string'?{name:p,platform:'Console'}:{name:p.displayName||p.username||p.name||'Unnamed survivor',platform:p.platform||p.device||'Console',playing:p.playing||'Rust Console'});return text.split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean).filter(x=>!/^players?\\s*$/i.test(x)).map((x,i)=>({name:x.replace(/^[-*]\\s*/, '').slice(0,80),platform:'Console',playing:'Rust Console'}));}
function rconRequest(profile,command='global.playerlist'){const {host,port}=parseEndpoint(profile);const scheme=String(process.env.RCON_TLS||'').toLowerCase()==='true'?'wss':'ws';const url=scheme+'://'+host+':'+port+'/'+encodeURIComponent(profile.rconPassword);return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);try{ws.close()}catch{};fn(v);};const timer=setTimeout(()=>finish(reject,Error('RCON timed out after 10 seconds')),10000);ws.on('open',()=>ws.send(JSON.stringify({Identifier:1,Message:command,Name:'WebRcon',Type:'Generic'})));ws.on('message',raw=>{try{const packet=JSON.parse(raw.toString());if(packet.Identifier===1||packet.Message!==undefined)finish(resolve,packet.Message??packet);}catch{finish(reject,Error('RCON returned invalid JSON'));}});ws.on('error',err=>finish(reject,Error('RCON connection failed: '+err.message)));ws.on('close',()=>{if(!done)finish(reject,Error('RCON closed before replying'));});});}
function parseJsonOrText(message){if(typeof message!=='string')return message;try{return JSON.parse(message);}catch{return {text:message};}}
async function fetchRconSnapshot(guildId){const p=serverProfiles.get(guildId);if(!p)throw Error('Run /pop setup and configure the Rust server first');if(!p.rconPassword)throw Error('RCON password is missing. Open /pop setup and click Add RCON password.');const optional=async(command)=>{try{return {ok:true,data:await rconRequest(p,command)};}catch(error){return {ok:false,error:error.message};}};const [infoResult,playersResult,statusResult,usersResult]=await Promise.all([optional('server.info'),optional('playerlist'),optional('status'),optional('users')]);if(!playersResult.ok)throw Error('playerlist failed: '+playersResult.error);const info=parseJsonOrText(infoResult.ok?infoResult.data:{});const players=parseJsonOrText(playersResult.data);const rows=parsePlayers(players?.players??players?.Players??players?.data?.players??playersResult.data);const current=Number(info?.players??info?.currentPlayers??info?.online??info?.playerCount??rows.length);const d={serverName:p.name,current:Number.isFinite(current)?current:rows.length,max:info?.maxPlayers??info?.maxplayers??info?.capacity??null,rows,info,status:statusResult.ok?statusResult.data:null,users:usersResult.ok?usersResult.data:null,queue:info?.queue??info?.joining??null,map:info?.map??info?.level??null,checks:{serverInfo:infoResult.ok,playerlist:playersResult.ok,status:statusResult.ok,users:usersResult.ok}};rconCache.set(guildId,{data:d,at:Date.now(),error:null});return d;}
async function fetchRcon(guildId){return (await fetchRconSnapshot(guildId));}
async function getPop(guildId){const hit=rconCache.get(guildId);if(hit&&Date.now()-hit.at<refreshMs)return hit.data;try{return await fetchRcon(guildId)}catch(e){if(hit){hit.error=e.message;return hit.data}throw e;}}
async function testRcon(guildId){return await fetchRconSnapshot(guildId);}
function normalizeSearchPlayer(raw){return {name:String(raw?.DisplayName??raw?.displayName??raw?.Username??raw?.username??raw?.name??'Unknown survivor'),platform:String(raw?.OsBrand??raw?.platform??raw?.Platform??raw?.device??'Console'),id:raw?.UserId??raw?.userId??raw?.Id??raw?.id??null,ping:Number.isFinite(Number(raw?.Ping??raw?.ping))?Number(raw.Ping??raw.ping):null,seconds:Number.isFinite(Number(raw?.ConnectedSeconds??raw?.connectedSeconds))?Number(raw.ConnectedSeconds??raw.connectedSeconds):null};}
async function searchPlayer(guildId,query){const p=serverProfiles.get(guildId);if(!p?.rconPassword)throw Error('RCON password is missing');const raw=await rconRequest(p,'playerlist');let parsed;try{parsed=typeof raw==='string'?JSON.parse(raw):raw;}catch{throw Error('RCON returned an unreadable player list');}const list=Array.isArray(parsed)?parsed:(parsed?.players||parsed?.Players||parsed?.data?.players);if(!Array.isArray(list))throw Error('RCON returned no readable players');const q=query.toLowerCase();return list.map(normalizeSearchPlayer).find(x=>x.name.toLowerCase().includes(q))||null;}
function searchCard(p,q){const platform=String(p.platform||'Console');const badge=platform.toLowerCase().includes('xbox')?'🟢 Xbox':platform.toLowerCase().includes('playstation')||platform.toLowerCase().includes('psn')?'🔵 PlayStation':'🎮 '+platform;const ping=p.ping===null?'⚪ Not returned':p.ping<80?'🟢 '+p.ping+' ms • Stable':p.ping<160?'🟡 '+p.ping+' ms • Fair':'🔴 '+p.ping+' ms • High';const session=p.seconds===null?'Not returned':p.seconds<3600?Math.max(1,Math.floor(p.seconds/60))+' min':Math.floor(p.seconds/3600)+'h '+Math.floor((p.seconds%3600)/60)+'m';return brand('🔎 PLAYER SIGNAL // PRIVATE').setColor(PURPLE).setDescription('**RUST CONSOLE NETWORK SEARCH**\n\n╭─ ACTIVE SURVIVOR LOCATED ─╮\n　Read-only live lookup from RCON.').addFields({name:'🎯 QUERY',value:q.slice(0,80),inline:true},{name:'🟢 PRESENCE',value:'Online & active',inline:true},{name:'🎮 GAMERTAG',value:p.name.slice(0,100),inline:true},{name:'🌐 CONSOLE NETWORK',value:badge,inline:true},{name:'📡 NETWORK LATENCY',value:ping,inline:true},{name:'⏳ ACTIVE SESSION',value:session,inline:true},{name:'🛡️ PLATFORM ID',value:p.id?'Available • hidden':'Not returned',inline:true},{name:'🔒 PRIVACY BOUNDARY',value:'No server address, port, region, credentials, profile links, or moderation actions are exposed.'}).setFooter({text:'RUST CONSOLE POP • Read-only operator panel'});}
const searchControls=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('search_refresh').setLabel('Refresh signal').setEmoji('🔄').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('search_dismiss').setLabel('Close panel').setEmoji('✖️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('search_privacy').setLabel('Privacy').setEmoji('🛡️').setStyle(ButtonStyle.Secondary));
const infoControls=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('info_terms').setLabel('Terms').setEmoji('📜').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('info_rules').setLabel('Rules').setEmoji('🛡️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('info_privacy').setLabel('Privacy').setEmoji('🔒').setStyle(ButtonStyle.Secondary));
const infoSections=()=>new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('info_section').setPlaceholder('Choose a section').addOptions({label:'Free access',value:'free',emoji:'🆓'},{label:'Data & privacy',value:'privacy',emoji:'🔐'},{label:'Safety',value:'safety',emoji:'⚠️'},{label:'RCON responsibility',value:'rcon',emoji:'🧰'}));
function termsEmbed(){return brand('📜 RUST CONSOLE POP // TERMS').setDescription('A free community tool for live Rust Console population visibility.').addFields({name:'🆓 Free to use',value:'The bot is provided free of charge. Availability, response time, and features may change.'},{name:'📡 Read-only by design',value:'Population and player details are read from the configured RCON source. This bot does not provide kick, ban, warning, or other moderation actions.'},{name:'🔐 Credentials',value:'RCON credentials must remain private. Never post passwords or tokens in public channels, issues, or GitHub.'},{name:'👑 Server owner control',value:'Only the Discord server owner can configure the server connection and automatic updates.'},{name:'📊 Live-data limits',value:'Counts and fields depend on what the server returns. Missing, delayed, or unavailable data is not fabricated.'},{name:'⚖️ Responsibility',value:'The server owner is responsible for RCON permissions, server access, local rules, and any use of displayed player information.'},{name:'🔒 Privacy boundary',value:'Do not use the bot to harass, dox, profile, or redistribute player information.'}).setFooter({text:'By using the bot, you agree to use it responsibly.'});}
function rulesEmbed(){return brand('🛡️ RUST CONSOLE POP // RULES').setDescription('Keep the feed useful, private, and safe for everyone.').addFields({name:'1 • Respect players',value:'No harassment, threats, doxxing, targeting, or sharing private player information.'},{name:'2 • No credential sharing',value:'Never post Discord tokens, RCON passwords, IPs, or private connection details.'},{name:'3 • No abuse',value:'Do not spam commands, scrape the service, probe servers, or attempt unauthorized access.'},{name:'4 • Read-only boundary',value:'The bot is for visibility and diagnostics. Do not expect or request moderation actions through it.'},{name:'5 • Follow server rules',value:'The Rust server owner’s rules and Discord’s Terms of Service always apply.'},{name:'6 • Report problems',value:'Share safe error messages and timestamps—never secrets or credentials.'}).setFooter({text:'Play fair • protect privacy • keep the coast clean'});}
const brand=t=>new EmbedBuilder().setColor(PURPLE).setTitle('☢️ '+t).setFooter({text:'RUST CONSOLE POP • Free • approved live source only'}).setTimestamp();
function dashboard(d, meta = {}) {
  const updated = meta.at || Date.now(); const stale = Boolean(meta.error); const count = Number.isFinite(Number(d.current)) ? Number(d.current) : d.rows.length;
  const e = brand('☢️ POP // LIVE SIGNAL').setDescription('**NEON PURPLE // RUST CONSOLE**\n\n' + (count === 0 ? '## 0 ONLINE\n🟢 The server is quiet right now.' : '## ' + count + ' ONLINE\n🔥 Survivors are active.') + (stale ? '\n⚠️ Showing the last successful snapshot.' : '')).addFields({name:'📡 STATUS',value:stale?'🟠 DELAYED':'🟢 LIVE',inline:true},{name:'🕒 CHECKED',value:'<t:'+Math.floor(updated/1000)+':R>',inline:true},{name:'🧑‍🚀 ROSTER',value:String(d.rows.length)+' listed',inline:true});
  const extras=[]; if(d.max!==null&&d.max!==undefined)extras.push('Capacity: **'+d.max+'**'); if(d.queue!==null&&d.queue!==undefined)extras.push('Queue: **'+d.queue+'**'); if(d.map)extras.push('Map: **'+String(d.map).slice(0,80)+'**'); if(extras.length)e.addFields({name:'📊 SERVER PULSE',value:extras.join('  •  ')});
  if(d.rows.length)e.addFields({name:'╔══ SURVIVORS ONLINE ══╗',value:d.rows.slice(0,20).map((p,i)=>'『'+String(i+1).padStart(2,'0')+'』 **'+val(p.name,'Survivor')+'**\n　🎮 '+val(p.platform,'Console')+'  •  '+val(p.playing,'Rust Console')+(p.ping?'  •  '+p.ping+'ms':'' )).join('\n\n').slice(0,3900)});else e.addFields({name:'╔══ SURVIVORS ONLINE ══╗',value:count===0?'╰─ No survivors detected. The coast is empty.':'╰─ No individual roster was returned.'});
  e.addFields({name:'🔒 PRIVACY',value:'Live population and player details only. Server address, port, region, credentials, and private configuration stay hidden.'}); return e;
}

const controls=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('refresh').setLabel('Refresh now').setEmoji('🔄').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('status').setLabel('RCON status').setEmoji('📡').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('copyless').setLabel('Privacy mode').setEmoji('🛡️').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('view_mode').setPlaceholder('Choose a dashboard view').addOptions({label:'Live roster',value:'roster',emoji:'🧑‍🚀'},{label:'Server pulse',value:'pulse',emoji:'📊'},{label:'How it works',value:'help',emoji:'❔'}))];
const setupButtons=(guildId)=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('server_add').setLabel(serverProfiles.has(guildId)?'Edit server':'Setup server').setEmoji(serverProfiles.has(guildId)?'🛠️':'🚀').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('server_view').setLabel('Review setup').setEmoji('📋').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('server_clear').setLabel('Disconnect').setEmoji('⛔').setStyle(ButtonStyle.Danger));
const rconSetupButton=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('rco_add').setLabel('Add RCON password').setEmoji('🔐').setStyle(ButtonStyle.Primary));
const updateSetup=()=>new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('setup').setPlaceholder('Choose how the live count should appear').addOptions({label:'Off',value:'off',emoji:'⏸️'},{label:'Bot status',value:'bio',emoji:'🟣'},{label:'Channel embed',value:'channel',emoji:'📣'},{label:'Both',value:'both',emoji:'⚡'}));
const serverModal=()=>new ModalBuilder().setCustomId('server_modal').setTitle('🛠️ Rust server details').addComponents(
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('server_name').setLabel('Server name').setPlaceholder('The name your players recognise').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('ip').setLabel('Server IP address').setPlaceholder('IPv4 address from your server host').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(80)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('rcon_port').setLabel('RCON port').setPlaceholder('RCON port from your host').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(10)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('region').setLabel('Region').setPlaceholder('Where this server is hosted').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(40)),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Description (optional)').setPlaceholder('A short description for this server').setStyle(TextInputStyle.Paragraph).setRequired(false).setMaxLength(500))
);
const credentialModal=()=>new ModalBuilder().setCustomId('credential_modal').setTitle('🔐 RCON credentials').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('rco_password').setLabel('RCON password').setPlaceholder('Entered privately — never posted').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(200)));
const profileCard=(p)=>brand('SERVER PROFILE // PRIVATE').setDescription('Configuration is restricted to the server owner. Sensitive connection details are redacted from this view.').addFields({name:'🧱 Server',value:p.name,inline:true},{name:'🔐 RCON',value:p.rconPassword?'Configured • hidden':'Not configured',inline:true},{name:'🛡️ Visibility',value:'Owner-only',inline:true},{name:'📝 Description',value:p.description||'No description'});
async function status(){const e=brand('POP STATUS').addFields({name:'Source configured',value:process.env.RUST_STATUS_URL?'✅ Yes':'❌ No',inline:true},{name:'Connection',value:cache.error?'🔴 Error':cache.data?'🟢 Healthy':'⚪ Not checked',inline:true},{name:'Last update',value:cache.at?'<t:'+Math.floor(cache.at/1000)+':R>':'Never',inline:true});if(cache.error)e.addFields({name:'Safe error',value:cache.error.slice(0,900)});return e;}
client.on('interactionCreate', async (i) => {
  try {
    if (i.isChatInputCommand()) {
      const sub = i.options.getSubcommand();
      if (i.commandName === 'terms') return i.reply({embeds:[termsEmbed()],components:[infoControls(),infoSections()],ephemeral:true});
      if (i.commandName === 'rules') return i.reply({embeds:[rulesEmbed()],components:[infoControls(),infoSections()],ephemeral:false});
      if (i.commandName === 'searchplayer') { if (!i.guild) return i.reply({content:'This command can only be used in a server.',ephemeral:true}); if (!i.memberPermissions?.has('ManageGuild') && i.guild.ownerId !== i.user.id) return i.reply({content:'🔒 Managers and the server owner only.',ephemeral:true}); const q=i.options.getString('username',true).trim(); if(!serverProfiles.get(i.guild.id)) return i.reply({content:'⚙️ Run /pop setup first.',ephemeral:true}); if(!serverProfiles.get(i.guild.id).rconPassword) return i.showModal(credentialModal()); await i.deferReply({ephemeral:true}); try {const p=await searchPlayer(i.guild.id,q); if(!p)return i.editReply({embeds:[brand('🔎 NO ACTIVE MATCH').setDescription('No connected player matched '+q+'.') ]}); const msg=await i.editReply({embeds:[searchCard(p,q)],components:[searchControls()]}); searchPanels.set(msg.id,{guildId:i.guild.id,query:q,ownerId:i.user.id});} catch(error){return i.editReply({embeds:[brand('🔎 SEARCH UNAVAILABLE').setColor(RED).setDescription('The live player list could not be read.').addFields({name:'Reason',value:String(error.message).slice(0,900)})]});} return; }
      if (sub === 'setup') {
        if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Only the Discord server owner can use /pop setup.', ephemeral: true });
        return i.reply({ embeds: [brand('SERVER CONTROL // OWNER PANEL').setDescription('One place to manage the Rust server behind this bot. Set the connection once, test it, then choose where the live population should appear.').addFields({ name: 'Connection', value: serverProfiles.has(i.guild.id) ? '🟢 Ready to test' : '⚪ Setup required', inline: true }, { name: 'Live count', value: config.get(i.guild.id) === 'off' || !config.get(i.guild.id) ? '⏸️ Disabled' : '🟢 ' + config.get(i.guild.id), inline: true }, { name: 'Recommended flow', value: serverProfiles.has(i.guild.id) ? 'Run /pop test, then choose an automatic update mode.' : 'Start with Edit server and enter the RCON details.' })], components: serverProfiles.get(i.guild.id)?.rconPassword ? [setupButtons(i.guild.id), updateSetup()] : [setupButtons(i.guild.id), rconSetupButton(), updateSetup()], ephemeral: true });
      }
      if (sub === 'test') {
        if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Only the Discord server owner can run the RCON test.', ephemeral: true });
        const profile = serverProfiles.get(i.guild.id);
        if (!profile) return i.reply({ content: '⚙️ Run /pop setup first and configure the Rust server.', ephemeral: true });
        if (!profile.rconPassword) return i.showModal(credentialModal());
        await i.deferReply({ ephemeral: true });
        try { const d = await testRcon(i.guild.id); return i.editReply({ embeds: [brand('RCON TEST PASSED').setDescription('✅ RCON connected and returned a player list.').addFields({ name: 'Server', value: d.serverName, inline: true }, { name: 'Players returned', value: String(d.current), inline: true }, { name: 'Next', value: 'Run /pop view.' })] }); }
        catch (error) { return i.editReply({ embeds: [brand('RCON TEST FAILED').setColor(RED).setDescription('❌ The bot could not connect or read the player list.').addFields({ name: 'Reason', value: String(error.message).slice(0, 900) }, { name: 'Check', value: 'Verify host/IP, RCON port, password, and provider settings.' })] }); }
      }
      if (sub === 'status') return i.reply({ embeds: [await status()], ephemeral: true });
      if (!i.guild) return i.reply({ content: 'This command can only be used in a Discord server.', ephemeral: true });
      const profile = serverProfiles.get(i.guild.id);
      if (!profile) return i.reply({ content: '⚙️ Run /pop setup first and configure the Rust server.', ephemeral: true });
      if (!profile.rconPassword) return i.showModal(credentialModal());
      await i.deferReply();
      try { const d = await getPop(i.guild.id); return i.editReply({ embeds: [dashboard(d, rconCache.get(i.guild.id) || {})], components: controls() }); }
      catch (error) { return i.editReply({ embeds: [brand('POP FEED OFFLINE').setColor(RED).setDescription('No live population was displayed.').addFields({ name: 'Reason', value: String(error.message).slice(0, 900) })] }); }
    }
    if (i.isButton() && ['info_terms','info_rules','info_privacy'].includes(i.customId)) { if(i.customId==='info_terms')return i.update({embeds:[termsEmbed()],components:[infoControls(),infoSections()]}); if(i.customId==='info_rules')return i.update({embeds:[rulesEmbed()],components:[infoControls(),infoSections()]}); return i.reply({embeds:[brand('🔒 PRIVACY').setDescription('Use only the live fields returned by RCON. Keep server connection details and credentials private. Do not redistribute player data.')],ephemeral:true}); }
    if (i.isButton() && (i.customId === 'search_refresh' || i.customId === 'search_dismiss')) { const panel=searchPanels.get(i.message.id); if(!panel||panel.ownerId!==i.user.id)return i.reply({content:'🔒 This private panel belongs to another operator.',ephemeral:true}); if(i.customId==='search_dismiss'){searchPanels.delete(i.message.id);return i.update({embeds:[brand('SEARCH CLOSED').setDescription('Private player panel closed.')],components:[]});} await i.deferUpdate(); try {const p=await searchPlayer(panel.guildId,panel.query); if(!p)return i.editReply({embeds:[brand('🔎 NO ACTIVE MATCH').setDescription('That player is no longer connected.')],components:[searchControls()]}); return i.editReply({embeds:[searchCard(p,panel.query)],components:[searchControls()]});} catch(error){return i.followUp({content:'⚠️ Refresh failed: '+String(error.message).slice(0,900),ephemeral:true});} }
    if (i.isButton()) {
      if (i.customId === 'server_add') { if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Owner only.', ephemeral: true }); try { return await i.showModal(serverModal()); } catch (error) { if (error?.code === 10062) return; throw error; } }
      if (i.customId === 'rco_add') { if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Owner only.', ephemeral: true }); try { return await i.showModal(credentialModal()); } catch (error) { if (error?.code === 10062) return; throw error; } }
      if (i.customId === 'server_view') { if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Owner only.', ephemeral: true }); const p = serverProfiles.get(i.guild.id); return i.reply({ embeds: [p ? profileCard(p) : brand('NO SERVER PROFILE').setDescription('Configure a server first.')], ephemeral: true }); }
      if (i.customId === 'server_clear') { if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Owner only.', ephemeral: true }); serverProfiles.delete(i.guild.id); return i.reply({ content: '🗑️ Rust server profile cleared from memory.', ephemeral: true }); }
      if (i.customId === 'status') return i.reply({ embeds: [await status()], ephemeral: true });
      if (i.customId === 'refresh') { await i.deferUpdate(); try { const d = await fetchRcon(i.guild.id); return i.editReply({ embeds: [dashboard(d, rconCache.get(i.guild.id) || {})], components: controls() }); } catch (error) { return i.followUp({ content: '⚠️ Live refresh failed: ' + String(error.message).slice(0, 900), ephemeral: true }); } }
    }
    if (i.isStringSelectMenu() && i.customId === 'view_mode') {
      const mode = i.values[0];
      if (mode === 'help') return i.reply({ embeds: [brand('POP // FIELD GUIDE').setDescription('🟣 **Live roster** shows player rows returned by RCON.\\n📊 **Server pulse** shows capacity, queue, and map when the server provides them.\\n🛡️ **Privacy mode** keeps connection details out of public embeds.')], ephemeral: true });
      const cached = rconCache.get(i.guild.id)?.data;
      if (!cached) return i.reply({ content: 'Run /pop view first to load the live signal.', ephemeral: true });
      if (mode === 'pulse') return i.update({ embeds: [brand('📊 SERVER PULSE').setDescription('**Rust Console operational snapshot**').addFields({ name: 'Online', value: String(cached.current), inline: true }, { name: 'Capacity', value: val(cached.max, 'Not returned'), inline: true }, { name: 'Queue', value: val(cached.queue, 'Not returned'), inline: true }, { name: 'Map', value: val(cached.map, 'Not returned') }, { name: 'Checks', value: 'server.info ' + (cached.checks?.serverInfo ? '✅' : '—') + '  playerlist ' + (cached.checks?.playerlist ? '✅' : '❌') + '  status ' + (cached.checks?.status ? '✅' : '—') + '  users ' + (cached.checks?.users ? '✅' : '—') })], components: controls() });
      return i.update({ embeds: [dashboard(cached, rconCache.get(i.guild.id) || {})], components: controls() });
    }
    if (i.isButton() && i.customId === 'copyless') return i.reply({ embeds: [brand('🛡️ PRIVACY MODE').setDescription('Public panels show population and returned player details only. IP, port, region, credentials, and private server configuration remain hidden.')], ephemeral: true });
    if (i.isStringSelectMenu() && i.customId === 'info_section') { const v=i.values[0]; const text=v==='free'?'🆓 The bot is free to use.':v==='privacy'?'🔐 Keep credentials and server details private.':v==='safety'?'⚠️ No abuse, scraping, harassment, or unauthorized access.':'🧰 The server owner controls RCON access and permissions.'; return i.reply({content:text,ephemeral:true}); }
    if (i.isModalSubmit()) {
      if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Only the Discord server owner can change setup.', ephemeral: true });
      if (i.customId === 'server_modal') {
        const p = { name: i.fields.getTextInputValue('server_name').trim(), ip: i.fields.getTextInputValue('ip').trim(), rconPort: i.fields.getTextInputValue('rcon_port').trim(), region: i.fields.getTextInputValue('region').trim(), description: i.fields.getTextInputValue('description').trim() };
        if (!/^\d{1,3}(?:\.\d{1,3}){3}$/.test(p.ip)) return i.reply({ content: '⚠️ Enter the Rust server IPv4 address only, for example 203.0.113.10.', ephemeral: true }); if (!/^\d{1,5}$/.test(p.rconPort) || Number(p.rconPort) < 1 || Number(p.rconPort) > 65535) return i.reply({ content: '⚠️ Enter a valid RCON port.', ephemeral: true });
        serverProfiles.set(i.guild.id, p);
        return i.reply({ content: '✅ Server details saved. Use **Edit server** any time to change them. Add the RCON password to finish the connection.', components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('rco_add').setLabel('Add RCON password').setEmoji('🔐').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId('server_add').setLabel('Edit server').setEmoji('🛠️').setStyle(ButtonStyle.Secondary))], ephemeral: true });
      }
      if (i.customId === 'credential_modal') { const p = serverProfiles.get(i.guild.id); if (!p) return i.reply({ content: 'Configure server details first.', ephemeral: true }); const password = i.fields.getTextInputValue('rco_password').trim(); if (!password) return i.reply({ content: '⚠️ Enter the RCON password before submitting.', ephemeral: true }); p.rconPassword = password; serverProfiles.set(i.guild.id, p); await i.deferReply({ ephemeral: true }); try { const d = await testRcon(i.guild.id); return i.editReply({ embeds: [brand('RCON CONNECTED').setDescription('✅ Password accepted. RCON connected and the player list is available.').addFields({ name: 'Server', value: d.serverName, inline: true }, { name: 'Players online', value: String(d.current), inline: true }, { name: 'Next', value: 'Run /pop view to open the full player list.' })] }); } catch (error) { p.rconPassword = undefined; serverProfiles.set(i.guild.id, p); return i.editReply({ embeds: [brand('RCON PASSWORD NOT VERIFIED').setColor(RED).setDescription('The password was saved only for this test, but the server rejected the connection.').addFields({ name: 'Reason', value: String(error.message).slice(0, 900) }, { name: 'Check', value: 'Confirm the RCON password, server IP, RCON port, and that RCON is enabled.' })] }); } }
    }
    if (i.isStringSelectMenu() && i.customId === 'setup') { if (i.guild?.ownerId !== i.user.id) return i.reply({ content: '🔒 Owner only.', ephemeral: true }); config.set(i.guild.id, i.values[0]); return i.update({ embeds: [brand('SETUP SAVED').setDescription('Automatic updates: **' + i.values[0] + '**')], components: [] }); }
  } catch (error) { console.error('[interaction]', error); if (!i.replied && !i.deferred) await i.reply({ content: '⚠️ Unexpected error. Check hosting logs.', ephemeral: true }); }
});
client.once('ready', () => {
  console.log('Rust Console Pop online as ' + client.user.tag);
  setInterval(async () => {
    for (const [guildId, mode] of config) {
      if (mode !== 'bio' && mode !== 'both') continue;
      try {
        const d = await getPop(guildId);
        client.user.setPresence({ activities: [{ name: (d.current ?? '—') + ' online • /pop' }], status: 'online' });
      } catch (error) {
        console.error('[bio]', error.message);
      }
    }
  }, refreshMs);
});
await client.login(process.env.DISCORD_TOKEN);
