import 'dotenv/config';
import {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder} from 'discord.js';
for (const k of ['DISCORD_TOKEN','CLIENT_ID']) if (!process.env[k]?.trim()) throw new Error('Missing '+k);
if (!/^\\d+$/.test(process.env.CLIENT_ID.trim())) throw new Error('CLIENT_ID must be numeric');
const PURPLE=0xb026ff, RED=0xed4245, refreshMs=Math.max(30,Number(process.env.RUST_REFRESH_SECONDS||60))*1000;
const config=new Map(), cache={data:null,at:0,error:null};
const command=new SlashCommandBuilder().setName('pop').setDescription('Rust Console live population dashboard').addSubcommand(s=>s.setName('view').setDescription('Show live population and available player details')).addSubcommand(s=>s.setName('status').setDescription('Show source connection health')).addSubcommand(s=>s.setName('setup').setDescription('Configure automatic updates; server owner only'));
const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN); const route=process.env.GUILD_ID?Routes.applicationGuildCommands(process.env.CLIENT_ID,process.env.GUILD_ID):Routes.applicationCommands(process.env.CLIENT_ID); await rest.put(route,{body:[command.toJSON()]});
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const val=(x,f='Unavailable')=>x===undefined||x===null||x===''?f:String(x);
function normalize(raw){const rows=Array.isArray(raw.players)?raw.players.map((p,i)=>typeof p==='string'?{name:p}:({name:p.name||p.username||'Unnamed survivor',platform:p.platform||p.device||'Platform unavailable',playing:p.playing||p.activity||'Rust Console'})):[];const n=raw.currentPlayers??raw.playersOnline??raw.online??raw.population??(Array.isArray(raw.players)?raw.players.length:null);return {serverName:raw.serverName||raw.name||process.env.RUST_SERVER_NAME||'Rust Console Server',current:Number.isFinite(Number(n))?Number(n):null,max:raw.maxPlayers??raw.capacity??null,rows};}
async function fetchPop(){if(!process.env.RUST_STATUS_URL)throw Error('RUST_STATUS_URL is not configured');const r=await fetch(process.env.RUST_STATUS_URL,{headers:{accept:'application/json'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Status source returned HTTP '+r.status);const d=normalize(await r.json());if(d.current===null&&!d.rows.length)throw Error('Status source returned no population field');cache.data=d;cache.at=Date.now();cache.error=null;return d;}
async function getPop(){if(cache.data&&Date.now()-cache.at<refreshMs)return cache.data;try{return await fetchPop()}catch(e){cache.error=e.message;if(cache.data)return cache.data;throw e;}}
const brand=t=>new EmbedBuilder().setColor(PURPLE).setTitle('☢️ '+t).setFooter({text:'RUST CONSOLE POP • Free • approved live source only'}).setTimestamp();
function dashboard(d){const e=brand('NEON POP // '+val(d.serverName)).setDescription('**🟣 LIVE RUST CONSOLE POPULATION**\\n'+(d.current===null?'Population unavailable':'**'+d.current+'** survivors online')+(d.max?' / '+d.max:'')+(cache.error?'\\n⚠️ Last successful snapshot':'')).addFields({name:'📡 Feed',value:cache.error?'Stale':'Connected',inline:true},{name:'🕒 Updated',value:cache.at?'<t:'+Math.floor(cache.at/1000)+':R>':'Unavailable',inline:true},{name:'🧑‍🚀 Player rows',value:String(d.rows.length),inline:true});if(d.rows.length)e.addFields({name:'SURVIVOR SIGNALS',value:d.rows.slice(0,20).map((p,i)=>'**'+(i+1)+'. '+val(p.name,'Survivor')+'**\\n🎮 '+val(p.platform)+' • '+val(p.playing)).join('\\n\\n').slice(0,3900)});else e.addFields({name:'SURVIVOR SIGNALS',value:'The approved source did not provide individual player rows. No names, platforms, avatars, or activities are invented.'});return e;}
const controls=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('refresh').setLabel('Refresh signal').setEmoji('🔄').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('status').setLabel('Connection status').setEmoji('📡').setStyle(ButtonStyle.Secondary));
const setup=()=>new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('setup').setPlaceholder('Choose automatic update mode').addOptions({label:'Off',value:'off',emoji:'⏸️'},{label:'Bot status',value:'bio',emoji:'🟣'},{label:'Channel embed',value:'channel',emoji:'📣'},{label:'Both',value:'both',emoji:'⚡'}));
async function status(){const e=brand('POP STATUS').addFields({name:'Source configured',value:process.env.RUST_STATUS_URL?'✅ Yes':'❌ No',inline:true},{name:'Connection',value:cache.error?'🔴 Error':cache.data?'🟢 Healthy':'⚪ Not checked',inline:true},{name:'Last update',value:cache.at?'<t:'+Math.floor(cache.at/1000)+':R>':'Never',inline:true});if(cache.error)e.addFields({name:'Safe error',value:cache.error.slice(0,900)});return e;}
client.on('interactionCreate',async i=>{try{if(i.isChatInputCommand()){const sub=i.options.getSubcommand();if(sub==='setup'){if(i.guild?.ownerId!==i.user.id)return i.reply({content:'🔒 Only the Discord server owner can use /pop setup.',ephemeral:true});return i.reply({embeds:[brand('POP SETUP').setDescription('Choose automatic live updates. Channel mode uses the server system channel.').addFields({name:'Current mode',value:config.get(i.guild.id)||'off'})],components:[setup()],ephemeral:true});}if(sub==='status')return i.reply({embeds:[await status()],ephemeral:true});await i.deferReply();try{const d=await getPop();return i.editReply({embeds:[dashboard(d)],components:[controls()]});}catch(e){return i.editReply({embeds:[brand('POP FEED OFFLINE').setColor(RED).setDescription('No live population was displayed because the approved source is unavailable.').addFields({name:'Reason',value:e.message},{name:'Next step',value:'Configure RUST_STATUS_URL with an approved public JSON status source.'})]});}}if(i.isButton()){if(i.customId==='status')return i.reply({embeds:[await status()],ephemeral:true});await i.deferUpdate();try{return i.editReply({embeds:[dashboard(await fetchPop())],components:[controls()]});}catch(e){return i.followUp({content:'⚠️ Live refresh failed: '+e.message,ephemeral:true});}}if(i.isStringSelectMenu()&&i.customId==='setup'){if(i.guild?.ownerId!==i.user.id)return i.reply({content:'🔒 Only the Discord server owner can change this.',ephemeral:true});config.set(i.guild.id,i.values[0]);return i.update({embeds:[brand('SETUP SAVED').setDescription('Automatic updates: **'+i.values[0]+'**')],components:[]});}}catch(e){console.error(e);if(!i.replied&&!i.deferred)i.reply({content:'⚠️ Unexpected error. Check hosting logs.',ephemeral:true});}});
client.once('ready',()=>{console.log('Rust Console Pop online as '+client.user.tag);}); await client.login(process.env.DISCORD_TOKEN);
